### ISSUE TITLE
worker run failed

### ISSUE THREAD

**Issue by ZianTT** [PKU-GeekGame/gs-backend#2]
help wanted
```
[2022-11-08 23:32:09 -0800] [17398] [ERROR] Exception occurred while handling uri: 'http://guiding_star_backend/service/wish/game_info?tabid=TGeN'
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/site-packages/sanic_ext/extensions/injection/constructor.py", line 55, in __call__
    retval = self.func(**args)
TypeError: <lambda>() missing 1 required positional argument: 'req'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "handle_exception", line 65, in handle_exception
    from sanic.http import Stage
  File "/www/wwwroot/guiding-star/src/api/app.py", line 49, in handle_error
    raise exc
  File "handle_request", line 41, in handle_request
    TypeVar,
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/site-packages/sanic/signals.py", line 197, in dispatch
    return await dispatch
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/site-packages/sanic/signals.py", line 167, in _dispatch
    retval = await maybe_coroutine
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/site-packages/sanic_ext/extensions/injection/injector.py", line 49, in inject_kwargs
    injected_args = await gather_args(
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/site-packages/sanic_ext/extensions/injection/constructor.py", line 158, in gather_args
    return {
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/site-packages/sanic_ext/extensions/injection/constructor.py", line 159, in <dictcomp>
    name: await do_cast(_type, constructor, request, **kwargs)
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/site-packages/sanic_ext/extensions/injection/constructor.py", line 170, in do_cast
    retval = await retval
  File "/root/.pyenv/versions/3.8.12/lib/python3.8/site-packages/sanic_ext/extensions/injection/constructor.py", line 61, in __call__
    raise ServerError(
sanic.exceptions.ServerError: Failure to inject dependencies. Make sure that all dependencies for '<lambda>' have been registered.
```
when requesting backend worker service, it return an 500 error and the exception is above.
how can i resolve it?

**Comment by xmcp** [comment]
What is your sanic and sanic-ext version?

```
$ pip freeze | grep sanic
sanic==21.12.2
sanic-ext==21.12.3
sanic-routing==0.7.2
```

**Comment by ZianTT** [comment]
```
# pip freeze | grep sanic
sanic==22.9.1
sanic-ext==22.9.1
sanic-routing==22.8.0
```
so it must be 21?

**Comment by xmcp** [comment]
sanic often add a lot of breaking changes across major versions. if downgrading to 22.12.2 fixes this issue, there should be some related breaking changes.

**Comment by ZianTT** [comment]
ok thats it.It works! Thanks!
